### ISSUE TITLE
Import with CommonJS

### ISSUE THREAD

**Issue by Mathie01** [localnerve/csp-hashes#5]
Hi !

Thank you for this library.
It's possible to import the library in CommonJS ?

Thanks!

**Comment by localnerve** [comment]
Yes, the output is transpiled to interoperate. Here's how to use plain old `require`:

```javascript
const hashstream = require('@localnerve/csp-hashes').default;
```

**Comment by localnerve** [comment]
FUTURE NOTE:
To use 2.0.0+ package version without ESM, you must use dynamic import:
```javascript
import('@localnerve/csp-hashes')
.then(({ default: hashstream }) => {
  hashstream({
    // options
  });
});
```
